### ISSUE TITLE
scala 2.13

### ISSUE THREAD

**Issue by francisdb** [stephennancekivell/scalatest-json#30]
I see only scala 2.11 and 2.12 versions are available

https://search.maven.org/search?q=scalatest-play-json

**Comment by stephennancekivell** [comment]
Hi, Im glad your liking the project. I've just published. I think it can be a while before it shows in the search.

https://repo1.maven.org/maven2/com/stephenn/scalatest-play-json_2.13/

**Comment by francisdb** [comment]
thanks!
