### ISSUE TITLE
Diff output could be nicer

### ISSUE THREAD

**Issue by francisdb** [stephennancekivell/scalatest-json#32]
see the examples from [diffx](https://github.com/softwaremill/diffx):

![image](https://user-images.githubusercontent.com/161305/66112052-67d9eb00-e5ca-11e9-8637-213b1e9f56ec.png)
from https://blog.softwaremill.com/human-readable-case-class-diffs-c707e83e08a2

**Comment by stephennancekivell** [comment]
Yea diffx looks great. How does it work for json structures though.

**Comment by baldram** [comment]
The `scalatest-jsoniter-scala` variant already uses `diffx`. It gives excellent output.
