### ISSUE TITLE
Upgrading Scalatest dependency (3.2.0)

### ISSUE THREAD

**Issue by baldram** [stephennancekivell/scalatest-json#85]
Hi Stephen,
it was a great idea with adopting the Skyscreamer JSONassert for Scala. Thank you. 
I have a question. 

The Scala was upgraded to 2.13.3 recently, however the Scalatest not. I see bunch of PRs by Scala Steward. One of them is regarding bumping the Scalatest dependency. Is there any bigger issue preventing from upgrading it to the latest one?

Best regards, 
Marcin

**Comment by stephennancekivell** [comment]
Hi, Marcin.

Na no real issue, just it takes a bit of manual work to publish the new version.

I would have thought you would be able to use the scalatest-json with a later version of scalatest or scala. Is there a compatibility breaking change somewhere.

Happy to publish the new one if you need.

Im glad you like the project :)

**Comment by baldram** [comment]
Hi Stephen, thank you for quick answer. I'm not yet sure whether there are any bigger incompatibility issues. Hopefully not 😉 Good to hear it's not a bigger problem for you. 
I asked you to be sure, whether the library is future proof. 
My idea would be to add a support for [Jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala) by Andriy @plokhotnyuk and then use in my project. I will check whether I'm able to handle it. If all is good, I will create another issue and PR with a solution. 

Best regards, 
Marcin

**Comment by stephennancekivell** [comment]
If you would like to submit a PR for Jsoniter. I'd be happy to publish it. Theres not much to each module.
I'll merge some of those scala steward lib bumps for you now.

**Comment by baldram** [comment]
Thank you!
